# Generated by Django 6.0.4 on 2026-05-16 02:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_securityevent_event_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='securityevent',
            name='request_path',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='securityevent',
            name='user_agent',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='securityevent',
            name='event_type',
            field=models.CharField(choices=[('login_success', 'Login bem-sucedido'), ('login_failure', 'Falha de login'), ('two_factor_challenge', 'Desafio 2FA enviado'), ('two_factor_success', '2FA validado'), ('two_factor_failure', 'Falha no 2FA'), ('token_issued', 'JWT emitido'), ('token_refreshed', 'Refresh token usado'), ('token_revoked', 'Refresh token revogado'), ('logout', 'Logout'), ('lockout', 'Bloqueio temporario'), ('signup', 'Cadastro'), ('throttle', 'Limitacao de frequencia'), ('user_created', 'Usuario criado'), ('user_deactivated', 'Usuario desativado'), ('user_reactivated', 'Usuario reativado'), ('user_blocked', 'Usuario bloqueado'), ('user_unblocked', 'Usuario desbloqueado'), ('message_reported', 'Mensagem reportada'), ('download', 'Arquivo baixado'), ('admin_access', 'Acesso administrativo'), ('permission_changed', 'Permissao alterada'), ('password_requested', 'Solicitacao de senha'), ('password_request_approved', 'Solicitacao de senha aprovada'), ('password_request_rejected', 'Solicitacao de senha recusada'), ('content_blocked', 'Conteudo bloqueado')], max_length=40),
        ),
        migrations.AddIndex(
            model_name='securityevent',
            index=models.Index(fields=['event_type', 'created_at'], name='core_securi_event_t_e93b36_idx'),
        ),
        migrations.AddIndex(
            model_name='securityevent',
            index=models.Index(fields=['user', 'created_at'], name='core_securi_user_id_5eb64f_idx'),
        ),
    ]
