# Generated by Django 6.0.4 on 2026-05-18 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_securityevent_request_path_securityevent_user_agent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='securityevent',
            name='event_type',
            field=models.CharField(choices=[('login_success', 'Login bem-sucedido'), ('login_failure', 'Falha de login'), ('two_factor_challenge', 'Desafio 2FA enviado'), ('two_factor_success', '2FA validado'), ('two_factor_failure', 'Falha no 2FA'), ('token_issued', 'JWT emitido'), ('token_refreshed', 'Refresh token usado'), ('token_revoked', 'Refresh token revogado'), ('logout', 'Logout'), ('lockout', 'Bloqueio temporario'), ('signup', 'Cadastro'), ('throttle', 'Limitacao de frequencia'), ('user_created', 'Usuario criado'), ('user_deactivated', 'Usuario desativado'), ('user_reactivated', 'Usuario reativado'), ('user_blocked', 'Usuario bloqueado'), ('user_unblocked', 'Usuario desbloqueado'), ('message_reported', 'Mensagem reportada'), ('download', 'Arquivo baixado'), ('admin_access', 'Acesso administrativo'), ('permission_changed', 'Permissao alterada'), ('password_requested', 'Solicitacao de senha'), ('password_request_approved', 'Solicitacao de senha aprovada'), ('password_request_rejected', 'Solicitacao de senha recusada'), ('health_record_updated', 'Ficha de saude atualizada'), ('health_appointment_scheduled', 'Agendamento de saude criado'), ('health_appointment_updated', 'Agendamento de saude atualizado'), ('health_consultation_recorded', 'Consulta de saude registrada'), ('content_blocked', 'Conteudo bloqueado')], max_length=40),
        ),
    ]
