# Generated by Django 6.0.5 on 2026-05-28 19:35

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Artwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('inventory_number', models.CharField(max_length=60, unique=True)),
                ('author', models.CharField(blank=True, max_length=140)),
                ('storage_location', models.CharField(blank=True, max_length=180)),
                ('photo', models.FileField(blank=True, upload_to='almoxarifado/quadros/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])])),
                ('condition_notes', models.CharField(blank=True, max_length=240)),
                ('notes', models.TextField(blank=True, max_length=1600)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_warehouse_artworks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name', 'inventory_number'],
            },
        ),
        migrations.CreateModel(
            name='ArtworkMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('saida', 'Saida / emprestimo'), ('entrada', 'Entrada / devolucao')], default='saida', max_length=20)),
                ('movement_date', models.DateField(default=django.utils.timezone.localdate)),
                ('taken_by', models.CharField(max_length=140)),
                ('phone_number', models.CharField(blank=True, max_length=24)),
                ('class_group', models.CharField(blank=True, max_length=120)),
                ('cpp_responsible', models.CharField(blank=True, max_length=120)),
                ('operator_name', models.CharField(blank=True, max_length=120)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('returned_at', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, max_length=1200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('artwork', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='warehouse.artwork')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_artwork_movements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-movement_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WarehouseActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_date', models.DateField()),
                ('activity_time', models.TimeField(blank=True, null=True)),
                ('activity_type', models.CharField(choices=[('aula', 'Aula'), ('exposicao', 'Exposicao'), ('reuniao', 'Reuniao'), ('oficina', 'Oficina'), ('avaliacao', 'Avaliacao')], default='exposicao', max_length=20)),
                ('responsible', models.CharField(blank=True, max_length=140)),
                ('status', models.CharField(choices=[('agendado', 'Agendado'), ('confirmado', 'Confirmado'), ('concluido', 'Concluido'), ('cancelado', 'Cancelado')], default='agendado', max_length=20)),
                ('notes', models.TextField(blank=True, max_length=1200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('artwork', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='warehouse.artwork')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_warehouse_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['activity_date', 'activity_time', 'artwork__name'],
            },
        ),
        migrations.CreateModel(
            name='WarehouseFollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followup_date', models.DateField(default=django.utils.timezone.localdate)),
                ('followup_time', models.TimeField(blank=True, null=True)),
                ('responsible', models.CharField(max_length=140)),
                ('reason', models.TextField(blank=True, max_length=1200)),
                ('action_taken', models.TextField(blank=True, max_length=1200)),
                ('support_material', models.CharField(blank=True, max_length=180)),
                ('return_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('concluido', 'Concluido'), ('aberto', 'Acompanhamento aberto'), ('andamento', 'Em acompanhamento')], default='aberto', max_length=20)),
                ('destination', models.CharField(blank=True, max_length=180)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('artwork', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followups', to='warehouse.artwork')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_warehouse_followups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-followup_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WarehouseStockItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(max_length=160)),
                ('item_class', models.CharField(blank=True, max_length=120)),
                ('batch', models.CharField(max_length=80)),
                ('unit', models.CharField(choices=[('unidades', 'Unidades'), ('caixas', 'Caixas'), ('pares', 'Pares'), ('frascos', 'Frascos'), ('ml', 'ml'), ('kg', 'kg')], default='unidades', max_length=20)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('minimum_quantity', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=160)),
                ('notes', models.TextField(blank=True, max_length=1200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_warehouse_stock_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['material', 'batch'],
                'constraints': [models.UniqueConstraint(fields=('material', 'batch'), name='unique_warehouse_stock_material_batch')],
            },
        ),
    ]
