# Generated by Django 6.0.4 on 2026-05-16 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_birth_date_user_last_two_factor_verified_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='background_theme',
            field=models.CharField(choices=[('terra', 'Terra'), ('mata', 'Mata'), ('ceu', 'Ceu'), ('noite', 'Noite'), ('semente', 'Semente')], default='terra', max_length=20),
        ),
    ]
