# Generated by Django 6.0.4 on 2026-05-18 12:30

from django.db import migrations, models


def migrate_legacy_security_role(apps, schema_editor):
    User = apps.get_model('accounts', 'User')
    User.objects.filter(role='security').update(role='admin', is_staff=True)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_background_theme'),
    ]

    operations = [
        migrations.RunPython(migrate_legacy_security_role, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('member', 'Membro'), ('collective', 'Coletivo'), ('moderator', 'Moderador'), ('admin', 'Administrador'), ('founder', 'Fundador')], default='member', max_length=20),
        ),
    ]
