# Generated by Django 6.0.4 on 2026-05-18 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_health_operator',
            field=models.BooleanField(default=False),
        ),
    ]
