# Generated by Django 6.0.5 on 2026-05-28 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_is_health_operator'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_rapporteur',
            field=models.BooleanField(default=False),
        ),
    ]
