# Generated by Django 6.0.5 on 2026-05-28 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_is_rapporteur'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_warehouse_operator',
            field=models.BooleanField(default=False),
        ),
    ]
