# Generated by Django 6.0.4 on 2026-05-16 01:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('body', models.TextField(max_length=1200)),
                ('is_pinned', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_community_notices', to=settings.AUTH_USER_MODEL)),
                ('community', models.ForeignKey(blank=True, limit_choices_to={'role': 'collective'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='community_notices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_pinned', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GroupActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('description', models.TextField(blank=True, max_length=1200)),
                ('activity_date', models.DateField()),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=120)),
                ('community', models.ForeignKey(blank=True, limit_choices_to={'role': 'collective'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_activities', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_group_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['activity_date', 'start_time', 'title'],
            },
        ),
        migrations.CreateModel(
            name='WeeklyTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('description', models.TextField(blank=True, max_length=600)),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('in_progress', 'Em andamento'), ('done', 'Concluida')], default='pending', max_length=20)),
                ('assignee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_tasks', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_weekly_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['due_date', 'status', 'title'],
            },
        ),
    ]
