# Generated by Django 6.0.4 on 2026-05-16 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_story_storyreaction_storyreply_storyview'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='age_rating',
            field=models.CharField(choices=[('free', 'Livre'), ('12', '12'), ('14', '14'), ('16', '16'), ('18', '18')], default='free', max_length=8),
        ),
        migrations.AddField(
            model_name='post',
            name='allow_download',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='allow_sharing',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='story',
            name='age_rating',
            field=models.CharField(choices=[('free', 'Livre'), ('12', '12'), ('14', '14'), ('16', '16'), ('18', '18')], default='free', max_length=8),
        ),
        migrations.AddField(
            model_name='story',
            name='allow_download',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='visibility',
            field=models.CharField(choices=[('public', 'Publico'), ('community', 'Comunidade'), ('followers', 'Amigos e seguidores'), ('private', 'Privado')], default='community', max_length=20),
        ),
        migrations.AlterField(
            model_name='story',
            name='visibility',
            field=models.CharField(choices=[('public', 'Publico'), ('community', 'Comunidade'), ('followers', 'Amigos e seguidores'), ('private', 'Privado'), ('custom', 'Lista personalizada')], default='community', max_length=20),
        ),
    ]
