# Generated by Django 6.0.5 on 2026-05-28 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0004_post_age_rating_post_allow_download_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='visibility',
            field=models.CharField(choices=[('public', 'Publico'), ('community', 'Comunidade'), ('followers', 'Amigos e seguidores'), ('private', 'Privado')], db_index=True, default='community', max_length=20),
        ),
        migrations.AlterField(
            model_name='story',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='expires_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='visibility',
            field=models.CharField(choices=[('public', 'Publico'), ('community', 'Comunidade'), ('followers', 'Amigos e seguidores'), ('private', 'Privado'), ('custom', 'Lista personalizada')], db_index=True, default='community', max_length=20),
        ),
    ]
